id: NetWitness Endpoint Test
version: -1
name: NetWitness Endpoint Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ffb051df-c09a-482d-8ab5-f6f9fd02e65b
    type: start
    task:
      id: ffb051df-c09a-482d-8ab5-f6f9fd02e65b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: df36223d-ac26-4eb8-8bc0-bc2cc00f9334
    type: regular
    task:
      id: df36223d-ac26-4eb8-8bc0-bc2cc00f9334
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: 0d6a63ef-10c5-4848-8180-fb4fd2df76bd
    type: regular
    task:
      id: 0d6a63ef-10c5-4848-8180-fb4fd2df76bd
      version: -1
      name: Get all machine data
      script: RSA NetWitness Endpoint|||netwitness-get-machines
      type: regular
      iscommand: true
      brand: RSA NetWitness Endpoint
    nexttasks:
      '#none#':
      - "3"
      - "4"
    scriptarguments:
      includeMachineData:
        simple: "yes"
      includeMachineIOCs:
        simple: "yes"
      includeMachineModules:
        simple: "yes"
      iocScoreGreaterThan: {}
      iocScoreLessThan: {}
      ipAdress: {}
      limit: {}
      macAddress: {}
      machineName:
        simple: NWE
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 07c813cc-cc46-4095-8672-c75b4886921e
    type: regular
    task:
      id: 07c813cc-cc46-4095-8672-c75b4886921e
      version: -1
      name: Get module
      script: RSA NetWitness Endpoint|||netwitness-get-machine-module
      type: regular
      iscommand: true
      brand: RSA NetWitness Endpoint
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      machineGUID:
        simple: ${NetWitness.Machines.MachineGUID}
      moduleID:
        simple: ${NetWitness.Modules.[0].ModuleID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 1f56e1a1-8aef-4c76-8d0a-432aa63f3da2
    type: condition
    task:
      id: 1f56e1a1-8aef-4c76-8d0a-432aa63f3da2
      version: -1
      name: Verify machine ID matches expected value
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      verified:
      - "5"
    separatecontext: false
    conditions:
    - label: verified
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: NetWitness.Machines.MachineGUID
            iscontext: true
          right:
            value:
              simple: ea946082-0563-c15e-8128-c5b6e8b2fea9
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
  "5":
    id: "5"
    taskid: ab96c09d-ffd1-4c48-8c6d-490ffdc78e6c
    type: title
    task:
      id: ab96c09d-ffd1-4c48-8c6d-490ffdc78e6c
      version: -1
      name: 'successful validation '
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
  "6":
    id: "6"
    taskid: 4ad40741-4c94-4164-8860-dc0ebb67e75f
    type: condition
    task:
      id: 4ad40741-4c94-4164-8860-dc0ebb67e75f
      version: -1
      name: Sample Outputs - Verify Existence Only
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      output exists:
      - "5"
    separatecontext: false
    conditions:
    - label: output exists
      condition:
      - - operator: isExists
          left:
            value:
              simple: NetWitness.Module.FullPath
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: File.MD5
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: NetWitness.Module.RiskScore
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
